music_directory         "/home/nebby/Music/mpd"
playlist_directory      "/home/nebby/Music/mpd/playlists"

sticker_file            "/home/nebby/.cache/mpd/sticker.db"

auto_update             "yes"
bind_to_address         "/tmp/mpd_socket"
restore_paused          "yes"
max_output_buffer_size  "16384"

audio_output {
    type "pulse"
    name "pulse"
}

audio_output {
    type "fifo"
    name "Visualizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
