set -sg escape-time 0

# Unbind the default Ctrl-b prefix
unbind C-b

# Set the new prefix to Ctrl-a
set-option -g prefix C-a

# Mouse scroll enable
set -g mouse on

# term
set -g default-terminal "tmux-256color"

# Bind Ctrl-a to send the new prefix (so Ctrl-a Ctrl-a sends a literal Ctrl-a)
bind-key C-a send-prefix

set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tpm'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run '~/.tmux/plugins/tpm/tpm'
